<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit14570e76ee4b33d4a8fe940818e3ccb3
{
    public static $files = array (
        'bf9f5270ae66ac6fa0290b4bf47867b7' => __DIR__ . '/..' . '/adodb/adodb-php/adodb.inc.php',
    );

    public static $prefixLengthsPsr4 = array (
        's' => 
        array (
            'sgoettsch\\monologRotatingFileHandler\\' => 37,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'PHPMailer\\PHPMailer\\' => 20,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
        ),
        'D' => 
        array (
            'DragonBe\\Vies\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'sgoettsch\\monologRotatingFileHandler\\' => 
        array (
            0 => __DIR__ . '/..' . '/sgoettsch/monolog-rotating-file-handler/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'DragonBe\\Vies\\' => 
        array (
            0 => __DIR__ . '/..' . '/dragonbe/vies/src/Vies',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'PHPGangsta_GoogleAuthenticator' => __DIR__ . '/..' . '/phpgangsta/googleauthenticator/PHPGangsta/GoogleAuthenticator.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit14570e76ee4b33d4a8fe940818e3ccb3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit14570e76ee4b33d4a8fe940818e3ccb3::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit14570e76ee4b33d4a8fe940818e3ccb3::$classMap;

        }, null, ClassLoader::class);
    }
}
