<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir)));

return array(
    'sgoettsch\\monologRotatingFileHandler\\' => array($vendorDir . '/sgoettsch/monolog-rotating-file-handler/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'PHPMailer\\PHPMailer\\' => array($vendorDir . '/phpmailer/phpmailer/src'),
    'Monolog\\' => array($vendorDir . '/monolog/monolog/src/Monolog'),
    'DragonBe\\Vies\\' => array($vendorDir . '/dragonbe/vies/src/Vies'),
);
